version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "1m" 
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      condition: any
      max_attempts: 3
      window: 120s
  networks:
    - mycorp
  volumes:
    - kvroot:/kvroot
    - data:/data

services:
  master-1:
    <<: *default-opts
    image: oracle-nosql/net
    hostname: master-1
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - NODE_TYPE=m
      - MASTER_NODE=master-1

  slave-1:
    <<: *default-opts
    image: oracle-nosql/net
    hostname: slave-1
    environment:
      - NODE_TYPE=s
      - MASTER_NODE=master-1

  slave-2:
    <<: *default-opts
    image: oracle-nosql/net
    hostname: slave-2
    environment:
      - NODE_TYPE=s
      - MASTER_NODE=master-1

networks:
  mycorp:

volumes: 
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/data/nosql/data"
  kvroot:
    driver: local
    driver_opts:
      type: one
      o: bind
      device: "/home/data/nosql/kvroot"
